baseurl = "/"
languageCode = "en-us"
title = "Seth Green's personal website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/setgree"
[[menu.main]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=66CRLeoAAAAJ"
[[menu.main]]
    name = "Blog"
    url = "https://setharielgreen.com"
[[menu.main]]
    name = "SoundCloud"
    url = "https://soundcloud.com/setgree/sets/quarantinep"


[params]
    description = "I am Seth Ariel Green and here you'll find some stuff I like and wrote"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
